---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-coil-cybozu-com-v2-addresspool
  failurePolicy: Fail
  name: maddresspool.kb.io
  rules:
  - apiGroups:
    - coil.cybozu.com
    apiVersions:
    - v2
    operations:
    - CREATE
    resources:
    - addresspools
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-coil-cybozu-com-v2-egress
  failurePolicy: Fail
  name: megress.kb.io
  rules:
  - apiGroups:
    - coil.cybozu.com
    apiVersions:
    - v2
    operations:
    - CREATE
    resources:
    - egresses
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-coil-cybozu-com-v2-addresspool
  failurePolicy: Fail
  name: vaddresspool.kb.io
  rules:
  - apiGroups:
    - coil.cybozu.com
    apiVersions:
    - v2
    operations:
    - CREATE
    - UPDATE
    resources:
    - addresspools
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-coil-cybozu-com-v2-egress
  failurePolicy: Fail
  name: vegress.kb.io
  rules:
  - apiGroups:
    - coil.cybozu.com
    apiVersions:
    - v2
    operations:
    - CREATE
    - UPDATE
    resources:
    - egresses
  sideEffects: None
