---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: coil-router
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
- apiGroups:
  - coil.cybozu.com
  resources:
  - addressblocks
  verbs:
  - get
  - list
  - watch
