---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: coild
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - coil.cybozu.com
  resources:
  - addressblocks
  verbs:
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - coil.cybozu.com
  resources:
  - blockrequests
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - coil.cybozu.com
  resources:
  - blockrequests/status
  verbs:
  - get
- apiGroups:
  - coil.cybozu.com
  resources:
  - egresses
  verbs:
  - get
  - list
  - watch
